// Code generated by "stringer -type Role,Page -linecomment -output stringers.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[roleUndefined-0]
	_ = x[RoleExternal-1]
	_ = x[RoleUser-2]
	_ = x[RoleModerator-3]
	_ = x[RoleAdmin-4]
	_ = x[RoleOwner-5]
	_ = x[roleEnd-6]
}

const _Role_name = "undefinedexternalusermodadminownernot-a-real-role"

var _Role_index = [...]uint8{0, 9, 17, 21, 24, 29, 34, 49}

func (i Role) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Role_index)-1 {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[idx]:_Role_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[pageUndefined-0]
	_ = x[pageLanding-1]
	_ = x[pageUsers-2]
	_ = x[pageWorkspaces-3]
	_ = x[pageDocuments-4]
	_ = x[pageMembers-5]
}

const _Page_name = "undefinedlandingusersworkspacesdocumentsmembers"

var _Page_index = [...]uint8{0, 9, 16, 21, 31, 40, 47}

func (i Page) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Page_index)-1 {
		return "Page(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Page_name[_Page_index[idx]:_Page_index[idx+1]]
}
